Fix namespace issue while volume list/delete
openebs/external-storage pull request #18
Opened 2017-12-23 14:19 UTC by prateekpandey14

There will be namespace passed while list and delete API calls to maya-apiserver.
Which is getting error out before if mayaapiserver and volumes are in different namespace

2017-12-23 14:54 UTC, AmitKumarDas requested changes

2017-12-23 14:54 UTC, AmitKumarDas commented on openebs/pkg/v1/maya_api.go
> +	req.Header.Set("namespace", namespace)
Err checking is missing

2017-12-23 14:54 UTC, AmitKumarDas commented on openebs/pkg/v1/maya_api.go
> +	req.Header.Set("namespace", namespace)
Err checking is missing

2017-12-23 14:54 UTC, AmitKumarDas commented on openebs/openebs-provisioner.go
> +	err = openebsVol.ListVolume(options.PVName, &volume, options.PVC.Namespace)
Namespace is the 2nd argument

2017-12-23 15:08 UTC, prateekpandey14 commented on openebs/pkg/v1/maya_api.go
> +	req.Header.Set("namespace", namespace)
done

2017-12-23 15:08 UTC, prateekpandey14 commented on openebs/pkg/v1/maya_api.go
> +	req.Header.Set("namespace", namespace)
done

2017-12-23 15:08 UTC, prateekpandey14 commented on openebs/openebs-provisioner.go
> +	err = openebsVol.ListVolume(options.PVName, &volume, options.PVC.Namespace)
done

2017-12-24 03:47 UTC, AmitKumarDas approved these changes

2017-12-25 05:00 UTC, kmova approved these changes
Thanks @prateekpandey14

2017-12-25 05:01 UTC, merged